# Generated by Django 5.2 on 2025-04-29 17:13

import django.db.models.deletion
import twin_scape_core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, null=True, storage=twin_scape_core.models.MinioStorage(), upload_to='')),
                ('video_file', models.FileField(blank=True, null=True, storage=twin_scape_core.models.MinioStorage(), upload_to='')),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed'), ('BUILDING', 'Building'), ('BUILDED', 'Builded'), ('RUNNING', 'Running')], default='READY', max_length=20)),
                ('ref_ply', models.CharField(blank=True, max_length=64, null=True)),
                ('ref_annotations', models.CharField(blank=True, max_length=64, null=True)),
                ('lesson_visibility', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='twin_scape_core.tag')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lesson',
                'db_table': 'Lesson',
                'permissions': [('can_create_lessons', 'Can create lessons'), ('can_view_lessons', 'Can view lessons')],
            },
        ),
    ]
