# Generated by Django 5.2.3 on 2025-06-25 14:55

import twin_scape_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_scape_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='splat_ply',
            field=models.FileField(blank=True, null=True, storage=twin_scape_core.models.MinioStorage(), upload_to=''),
        ),
    ]
