# Generated by Django 5.2 on 2025-04-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_scape_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed'), ('BUILDING', 'Building'), ('BUILDED', 'Builded'), ('RUNNING', 'Running'), ('ENQUEUED', 'Enqueued')], default='READY', max_length=20),
        ),
    ]
