# Generated by Django 5.2.3 on 2025-06-25 15:04

import twin_scape_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_scape_core', '0002_lesson_splat_ply'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='annotation_ply',
            field=models.FileField(blank=True, null=True, storage=twin_scape_core.models.MinioStorage(), upload_to=''),
        ),
    ]
