# Generated by Django 5.2 on 2025-04-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_scape_core', '0002_alter_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='build_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
