# Generated by Django 5.2 on 2025-04-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_scape_core', '0003_lesson_build_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed'), ('BUILDING', 'Building'), ('BUILT', 'Built'), ('RUNNING', 'Running'), ('ENQUEUED', 'Enqueued')], default='READY', max_length=20),
        ),
    ]
